import React, { useState } from "react";
import Lightbox from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";
import Zoom from "yet-another-react-lightbox/plugins/zoom";

function Portfolio({ src, title, allImages = [], currentIndex = 0 }) {
  const [open, setOpen] = useState(false);

  return (
    <>
      <figure className="grid-item">
        <div
          onClick={() => setOpen(true)}
          style={{ overflow: 'hidden', borderRadius: '4px', cursor: 'pointer' }}
        >
          <img src={src} alt={title} loading="lazy" />
        </div>
        <figcaption>{title}</figcaption>
      </figure>

      <Lightbox
        open={open}
        close={() => setOpen(false)}
        index={currentIndex}
        slides={allImages} 
        plugins={[Zoom]}
        zoom={{ maxZoomPixelRatio: 4, scrollToZoom: true }}

        on={{
          click: ({ target, currentTarget }) => {
            if (target === currentTarget) {
              setOpen(false);
            }
          }
        }}

        // FIX: Use slideContainer to wrap the native image instead of replacing it
        render={{
          slideContainer: ({ slide, children }) => {
            return (
              <div className="yarl__picture_container">
                {/* children renders the native library image with perfect sizing */}
                {children}
                
                {/* The overlay bar locked identically to the picture boundaries */}
                <div className="my-picture-attached-bar">
                  <h4>{slide.title}</h4>
                </div>
              </div>
            );
          }
        }}

        styles={{
          container: { backgroundColor: "rgba(10, 10, 10, 0.95)" }
        }}
      />

      {/* THE CSS REMAINS IDENTICAL TO PROTECT YOUR DESIGN */}
      <style>{`
  /* 1. Wrapper that preserves native image sizes and scales */
  .yarl__picture_container {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
  }

  /* 2. Target the native wrapper generated by 'children' to pin the bar to its bottom */
  .yarl__picture_container > .yarl__slide_image_container {
    position: relative !important;
    /* FIX: This adds a safe zone beneath the image so it physically cannot bleed into your text bar */
    padding-bottom: 70px !important; 
    box-sizing: border-box;
  }

  /* 3. Position the bar safely at the bottom of the new cushioned container */
  .my-picture-attached-bar {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    /* FIX: Height adjusted to 70px to perfectly match and fill the padding cushion area */
    height: 70px; 
    background: linear-gradient(to top, rgba(0, 0, 0, 0.85) 0%, rgba(0, 0, 0, 0.4) 100%);
    padding: 0 20px;
    box-sizing: border-box;
    display: flex;
    justify-content: center;
    align-items: center;
    pointer-events: none;
    z-index: 2;
  }

  /* Style the inner header text uniformly */
  .my-picture-attached-bar h4 {
    margin: 0;
    font-size: 1.2rem;
    font-weight: 500;
    letter-spacing: 0.5px;
    color: #ffffff;
    text-align: center;
    font-family: sans-serif;
  }
`}</style>

    </>
  );
}

export default Portfolio;
